### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by ChristopherGSA** [hitchdev/hitchstory#2]
Hi @crdoconnor 

I'm thinking of using hitchstory for another project (remember we met at Babylon).

I was going to run through the tests and check everything was working with Python 3.9 (maybe 3.10). What's the best way for me to get setup for contributing? Happy to write this up in a contributing guide.

Cheers!

**Comment by ChristopherGSA** [comment]
Gonna hold off for now

**Comment by crdoconnor** [comment]
Hi Chris,

Of course I remember. Thanks again for inviting me in!

It should be relatively simple, but I need to check that the environment
set up scripts for the tests still run. I will double check tomorrow and
get back to you.

**Comment by crdoconnor** [comment]
Hi,

Sorry it's taking a bit longer than expected to fix up the tests. I should
have something functioning tomorrow evening though.
